# Generated by Django 4.2.30 on 2026-05-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guestbook", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
